In [1]:
import pandas as pd

In [122]:
dfb = pd.read_csv('aiocouchdb-0.5.0_bandit.txt')

In [123]:
dfb = dfb[['test_name', 'test_id', 'issue_severity', 'issue_confidence', 'line_number', 'line_range']]

In [124]:
dfb

,test_name,test_id,issue_severity,issue_confidence,line_number,line_range
0,assert_used,B101,LOW,HIGH,142,"[142, 143]"
1,assert_used,B101,LOW,HIGH,35,"[35, 36]"
2,assert_used,B101,LOW,HIGH,330,[330]
3,assert_used,B101,LOW,HIGH,340,[340]
4,assert_used,B101,LOW,HIGH,102,[102]
5,assert_used,B101,LOW,HIGH,103,[103]
6,assert_used,B101,LOW,HIGH,104,"[104, 105]"
7,assert_used,B101,LOW,HIGH,172,[172]
8,assert_used,B101,LOW,HIGH,173,"[173, 174]"
9,assert_used,B101,LOW,HIGH,181,[181]
10,assert_used,B101,LOW,HIGH,211,[211]
11,assert_used,B101,LOW,HIGH,212,"[212, 213]"
12,assert_used,B101,LOW,HIGH,88,"[88, 89]"
13,assert_used,B101,LOW,HIGH,105,"[105, 106]"
14,assert_used,B101,LOW,HIGH,150,[150]
15,assert_used,B101,LOW,HIGH,359,[359]
16,assert_used,B101,LOW,HIGH,339,[339]
17,blacklist,B303,MEDIUM,HIGH,75,[75]
18,blacklist,B303,MEDIUM,HIGH,87,[87]
19,blacklist,B303,MEDIUM,HIGH,98,[98]
20,hardcoded_password_funcarg,B106,LOW,MEDIUM,126,"[126, 127]"
21,hardcoded_password_funcarg,B106,LOW,MEDIUM,136,"[136, 137]"
22,hardcoded_password_funcarg,B106,LOW,MEDIUM,144,"[144, 145]"
23,assert_used,B101,LOW,HIGH,40,[40]
24,assert_used,B101,LOW,HIGH,49,[49]
25,assert_used,B101,LOW,HIGH,57,[57]
26,assert_used,B101,LOW,HIGH,61,"[61, 62]"
27,assert_used,B101,LOW,HIGH,71,[71]

In [32]:
df = pd.read_csv('bandit parser/bandit_parser.out')

In [37]:
df = df[['test_name', 'test_id', 'issue_severity', 'issue_confidence', 'line_number', 'line_range']]

In [38]:
df

,test_name,test_id,issue_severity,issue_confidence,line_number,line_range
0,blacklist,B303,MEDIUM,HIGH,371,[371]
1,blacklist,B303,MEDIUM,HIGH,378,[378]
2,blacklist,B303,MEDIUM,HIGH,379,[379]
3,assert_used,B101,LOW,HIGH,625,"[625, 626]"
4,assert_used,B101,LOW,HIGH,218,[218]
5,assert_used,B101,LOW,HIGH,504,[504]
6,assert_used,B101,LOW,HIGH,54,[54]
7,assert_used,B101,LOW,HIGH,930,[930]
8,assert_used,B101,LOW,HIGH,1035,[1035]
9,blacklist,B404,LOW,HIGH,9,[9]
10,assert_used,B101,LOW,HIGH,139,"[139, 140]"
11,start_process_with_no_shell,B606,LOW,MEDIUM,152,[152]
12,start_process_with_partial_path,B607,LOW,HIGH,155,[155]
13,subprocess_without_shell_equals_true,B603,LOW,HIGH,155,[155]
14,start_process_with_partial_path,B607,LOW,HIGH,158,[158]
15,subprocess_without_shell_equals_true,B603,LOW,HIGH,158,[158]
16,blacklist,B322,HIGH,HIGH,176,[176]

In [39]:
# number of total issues
# number of test categories flagged
# number of low/medium/high for severity and confidence
# number of overlapping lines

In [41]:
## Preliminary explanation of bandit and pylint output
# bar chart with test names, types of errors
# pie chart for low/med/high severity and confidence
# for bandit: filter out low confidence

In [42]:
## Stats
# regression/correlation on number of pylint issues vs number of bandit issues 
# (if time; find covariates like program size)
# split by pylint category and bandit test name, severity level

# num high severity security issues = beta_1 * I + beta_2 * R + ... -> learn the betas (weights) for pylint categories
# then do this for specific categories of security issues - blaclist, subprocess, etc

# If time: PCA of matrix with bandit vs all the repos, do 6 clusters

In [116]:
lintdf = pd.read_csv('quilt7_pylint.txt')
lintdf # We only care about the 0th row aka "globals" - tells us the total I's, R's, etc for that project (in this example, quilt)

    I  R   C   W   E  F
0   5  1  38  21  28  0
1   0  0   0   0   2  0
2   0  0   0   0   0  0
3   0  0   0   0   0  0
4   0  0   0   0   1  0
5   0  0   4   1   6  0
6   0  0   0   0   1  0
7   0  0   0   0   0  0
8   0  0   0   0   1  0
9   3  0   3   2   4  0
10  0  0   0   0   1  0
11  0  0   0   0   1  0
12  0  1   4   0   6  0
13  2  0  21   8   4  0
14  0  0   0   0   1  0
15  0  0   6  10   0  0

In [128]:
pd.read_csv('aiocouchdb-0.5.0_pylint.txt')

    I   R    C   W    E  F
0   0   0    1   0    7  0
1   0   0    0   0    0  0
2   0   0    0   0    1  0
3   0   0    0   0    1  0
4   0   0    0   0    1  0
5   0   0    0   0    1  0
6   0   0    0   0    1  0
7   0   0    0   0    1  0
8   0   3    0   0    1  0
9   0   0    0   0    1  0
10  0   0    0   0    1  0
11  0   0    0   0    1  0
12  0   0    0   0    0  0
13  0   1   41   4   16  0
14  0   0   27   7   14  0
15  0   2   33   0   30  0
16  0   3   68   0   27  0
17  0   2   39   0   49  0
18  0   0    0   0    1  0
19  0   0   10   0   14  0
20  0   0   34   0   27  0
21  0   3   61   6   53  0
22  0   2   37   1   26  0
23  0   0   11   3    9  0
24  0   0    1   1    0  0
25  0   0    0   0    1  0
26  0   0   24   1    0  0
27  0  16  393  23  284  0
28  0   0    6   0    0  0

In [129]:
# ^In this example, it's the second-to-last row that has the totals. We only need that row